fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener:
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' } 